# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ddb2d9c245d4acf66daa8ca9a144e5ff6fd9de89e6a1d6e2d7204cccc1613d9af8a0c986c23912d5018a8e40f2dd9a19e32a07b3a05b0f2153b0fc4eb4472e48

test:
  secret_key_base: 37b7c71c699862785010d77d5fbe1e5511ff96feee2069dfc006e33b495b543c5fea779e0c2363cd912ae300449b53eeb141f79ac5b144f33836337583d0c0f1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
